# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-04 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('website', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('team_selection', models.CharField(choices=[('T1', 'Team 1'), ('T2', 'Team 2'), ('T3', 'Team 3'), ('T4', 'Team 4'), ('T5', 'Team 5'), ('T6', 'Team 6'), ('T7', 'Team 7'), ('T8', 'Team 8'), ('T9', 'Team 9'), ('T10', 'Team 10'), ('T11', 'Team 11'), ('T12', 'Team 12'), ('T13', 'Team 13'), ('T14', 'Team 14'), ('T15', 'Team 15'), ('T16', 'Team 16'), ('T17', 'Team 17'), ('T18', 'Team 18'), ('T19', 'Team 19'), ('T20', 'Team 20'), ('T21', 'Team 21'), ('T22', 'Team 22'), ('T23', 'Team 23'), ('T24', 'Team 24'), ('T25', 'Team 25')], default='T1', max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('golf_handicap', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('disclaimer', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
