# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-01 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180927_1444'),
        ('website', '0007_homepage_violator'),
    ]

    operations = [
    ]
