# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('website', '0008_merge_20181001_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', wagtail.core.fields.StreamField((('person', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('name', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('bio', wagtail.core.blocks.RichTextBlock()), ('featured', wagtail.core.blocks.BooleanBlock(help_text='Select to display this person more prominently', required=False))))),))),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Leadership',
            },
        ),
    ]
