# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_peoplesettings'),
        ('website', '0010_auto_20181002_1621'),
    ]

    operations = [
    ]
