# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20181009_1422'),
        ('website', '0012_auto_20181005_1401'),
    ]

    operations = [
    ]
