# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mediatext.blocks.videocopy
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20181005_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeIntroVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('video_block', wagtail.core.fields.StreamField((('video', mediatext.blocks.videocopy.LoopingVideoChooserBlock()),))),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_videos', to='website.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
