# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20181009_1738'),
        ('website', '0013_homeintrovideos'),
    ]

    operations = [
    ]
