# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20181009_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksamplepage',
            name='client_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worksamplepage',
            name='featured_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='worksamplepage',
            name='work_title',
            field=models.CharField(max_length=255),
        ),
    ]
