# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20181010_1912'),
        ('website', '0017_auto_20181010_1551'),
    ]

    operations = [
    ]
