# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20181012_1719'),
        ('website', '0019_auto_20181011_2025'),
    ]

    operations = [
    ]
