# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20181102_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='headline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='published_by',
            field=models.CharField(max_length=255),
        ),
    ]