# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20181102_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksamplepage',
            name='ghost_page',
            field=models.BooleanField(default=False, help_text='If checked, this page will be hidden throughout the site, but will remain accessible via its URL.'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='headline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='published_by',
            field=models.CharField(max_length=255),
        ),
    ]
