# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-24 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_work_sample_grid_block'),
        ('website', '0024_auto_20181107_2258'),
    ]

    operations = [
    ]