# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20181018_2055'),
        ('website', '0024_auto_20181018_1851'),
    ]

    operations = [
    ]
