# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-07 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('website', '0026_merge_20191024_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_animation', models.CharField(blank=True, choices=[(None, 'None'), ('anim willFadeIn', 'Fade in'), ('anim willFadeFromTop', 'Fade in from top'), ('anim willFadeFromRight', 'Fade in from right'), ('anim willFadeFromBottom', 'Fade in from bottom'), ('anim willFadeFromLeft', 'Fade in from left')], default=None, max_length=25, null=True)),
                ('secondary_animation', models.CharField(blank=True, choices=[(None, 'None'), ('anim willFadeIn', 'Fade in'), ('anim willFadeFromTop', 'Fade in from top'), ('anim willFadeFromRight', 'Fade in from right'), ('anim willFadeFromBottom', 'Fade in from bottom'), ('anim willFadeFromLeft', 'Fade in from left')], default=None, max_length=25, null=True)),
                ('tertiary_animation', models.CharField(blank=True, choices=[(None, 'None'), ('anim willFadeIn', 'Fade in'), ('anim willFadeFromTop', 'Fade in from top'), ('anim willFadeFromRight', 'Fade in from right'), ('anim willFadeFromBottom', 'Fade in from bottom'), ('anim willFadeFromLeft', 'Fade in from left')], default=None, max_length=25, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Animations Settings',
            },
        ),
    ]
