# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-07 18:09
from __future__ import unicode_literals

from django.db import migrations
import mediatext.blocks.videocopy
import wagtail.core.fields
import website.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_merge_20191024_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksamplepage',
            name='featured_video',
            field=wagtail.core.fields.StreamField((('looping_video', mediatext.blocks.videocopy.LoopingVideoChooserBlock()), ('looping_lazy_video', website.blocks.LoopingLazyVideoChooserBlock())), blank=True),
        ),
    ]
