# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20181022_1358'),
        ('website', '0027_auto_20181018_2215'),
    ]

    operations = [
    ]
