# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-18 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20200107_1528'),
        ('website', '0027_animationsettings'),
    ]

    operations = [
    ]
