# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_newspage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='article_url',
            field=models.URLField(blank=True, help_text='A link to the original article', null=True),
        ),
    ]
