# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_newspage_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='author',
            field=models.CharField(default='John Doe', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspage',
            name='headline',
            field=models.CharField(default='Default headline', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspage',
            name='published_by',
            field=models.CharField(default='Default source', max_length=255),
            preserve_default=False,
        ),
    ]
