# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20181022_2127'),
        ('website', '0029_auto_20181022_1639'),
    ]

    operations = [
    ]
