# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 15:06
from __future__ import unicode_literals

from django.db import migrations
import mediatext.blocks.videocopy
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20181023_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeintrovideos',
            name='video_block_landscape',
            field=wagtail.core.fields.StreamField((('video', mediatext.blocks.videocopy.LoopingVideoChooserBlock()),), blank=True),
        ),
        migrations.AddField(
            model_name='homeintrovideos',
            name='video_block_portrait',
            field=wagtail.core.fields.StreamField((('video', mediatext.blocks.videocopy.LoopingVideoChooserBlock()),), blank=True),
        ),
    ]
