# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20181025_2123'),
        ('website', '0018_auto_20181026_1414'),
    ]

    operations = [
    ]
