# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_auto_20181026_2120'),
        ('website', '0044_careerspage_closing_content'),
    ]

    operations = [
    ]
