# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 17:45
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_tinderpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinderpage',
            name='tinder_attributes',
            field=wagtail.core.fields.StreamField((('attributes', wagtail.core.blocks.StructBlock((('attribute_icon', wagtail.core.blocks.ChoiceBlock(choices=[('location', 'location'), ('occupation', 'occupation'), ('education', 'education'), ('interests', 'interests'), ('bio', 'bio')])), ('text', wagtail.core.blocks.CharBlock())))),), blank=True),
        ),
    ]
