# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('website', '0049_auto_20181029_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinderpage',
            name='dislike_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='tinderpage',
            name='like_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='tinderpage',
            name='tinder_attributes',
            field=wagtail.core.fields.StreamField((('attributes', wagtail.core.blocks.StructBlock((('attribute_icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))),), blank=True),
        ),
    ]
