# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 19:12
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_auto_20181030_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='announcements',
            field=wagtail.core.fields.StreamField((('violator_announcement', wagtail.snippets.blocks.SnippetChooserBlock('overlay.ViolatorAnnouncement')),), blank=True, help_text='(Optional) Select up to 2 announcements to display in a violator. To create an announcement, go to Snippets > Violator Announcements', null=True, verbose_name='Announcement Violator'),
        ),
        migrations.AddField(
            model_name='careerspage',
            name='announcements',
            field=wagtail.core.fields.StreamField((('violator_announcement', wagtail.snippets.blocks.SnippetChooserBlock('overlay.ViolatorAnnouncement')),), blank=True, help_text='(Optional) Select up to 2 announcements to display in a violator. To create an announcement, go to Snippets > Violator Announcements', null=True, verbose_name='Announcement Violator'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='announcements',
            field=wagtail.core.fields.StreamField((('violator_announcement', wagtail.snippets.blocks.SnippetChooserBlock('overlay.ViolatorAnnouncement')),), blank=True, help_text='(Optional) Select up to 2 announcements to display in a violator. To create an announcement, go to Snippets > Violator Announcements', null=True, verbose_name='Announcement Violator'),
        ),
        migrations.AddField(
            model_name='disciplinepage',
            name='announcements',
            field=wagtail.core.fields.StreamField((('violator_announcement', wagtail.snippets.blocks.SnippetChooserBlock('overlay.ViolatorAnnouncement')),), blank=True, help_text='(Optional) Select up to 2 announcements to display in a violator. To create an announcement, go to Snippets > Violator Announcements', null=True, verbose_name='Announcement Violator'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='announcements',
            field=wagtail.core.fields.StreamField((('violator_announcement', wagtail.snippets.blocks.SnippetChooserBlock('overlay.ViolatorAnnouncement')),), blank=True, help_text='(Optional) Select up to 2 announcements to display in a violator. To create an announcement, go to Snippets > Violator Announcements', null=True, verbose_name='Announcement Violator'),
        ),
        migrations.AddField(
            model_name='jobdetailspage',
            name='announcements',
            field=wagtail.core.fields.StreamField((('violator_announcement', wagtail.snippets.blocks.SnippetChooserBlock('overlay.ViolatorAnnouncement')),), blank=True, help_text='(Optional) Select up to 2 announcements to display in a violator. To create an announcement, go to Snippets > Violator Announcements', null=True, verbose_name='Announcement Violator'),
        ),
        migrations.AddField(
            model_name='leadershippage',
            name='announcements',
            field=wagtail.core.fields.StreamField((('violator_announcement', wagtail.snippets.blocks.SnippetChooserBlock('overlay.ViolatorAnnouncement')),), blank=True, help_text='(Optional) Select up to 2 announcements to display in a violator. To create an announcement, go to Snippets > Violator Announcements', null=True, verbose_name='Announcement Violator'),
        ),
        migrations.AddField(
            model_name='newslandingpage',
            name='announcements',
            field=wagtail.core.fields.StreamField((('violator_announcement', wagtail.snippets.blocks.SnippetChooserBlock('overlay.ViolatorAnnouncement')),), blank=True, help_text='(Optional) Select up to 2 announcements to display in a violator. To create an announcement, go to Snippets > Violator Announcements', null=True, verbose_name='Announcement Violator'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='announcements',
            field=wagtail.core.fields.StreamField((('violator_announcement', wagtail.snippets.blocks.SnippetChooserBlock('overlay.ViolatorAnnouncement')),), blank=True, help_text='(Optional) Select up to 2 announcements to display in a violator. To create an announcement, go to Snippets > Violator Announcements', null=True, verbose_name='Announcement Violator'),
        ),
        migrations.AddField(
            model_name='tinderpage',
            name='announcements',
            field=wagtail.core.fields.StreamField((('violator_announcement', wagtail.snippets.blocks.SnippetChooserBlock('overlay.ViolatorAnnouncement')),), blank=True, help_text='(Optional) Select up to 2 announcements to display in a violator. To create an announcement, go to Snippets > Violator Announcements', null=True, verbose_name='Announcement Violator'),
        ),
        migrations.AddField(
            model_name='workpage',
            name='announcements',
            field=wagtail.core.fields.StreamField((('violator_announcement', wagtail.snippets.blocks.SnippetChooserBlock('overlay.ViolatorAnnouncement')),), blank=True, help_text='(Optional) Select up to 2 announcements to display in a violator. To create an announcement, go to Snippets > Violator Announcements', null=True, verbose_name='Announcement Violator'),
        ),
        migrations.AddField(
            model_name='worksamplepage',
            name='announcements',
            field=wagtail.core.fields.StreamField((('violator_announcement', wagtail.snippets.blocks.SnippetChooserBlock('overlay.ViolatorAnnouncement')),), blank=True, help_text='(Optional) Select up to 2 announcements to display in a violator. To create an announcement, go to Snippets > Violator Announcements', null=True, verbose_name='Announcement Violator'),
        ),
    ]
